#include <stdio.h>
#include <stlib.h>

SalaAula criaSala(int fileiras, int carteiras)
{
  
}

boolean destroiSala(){
  
}  

boolean adicionaAluno(String nome, int fileira, int carteira){
  
}  

boolean moveAluno(int fileiraAtual, int carteiraAtual, int novaFileira, int novaCarteira){
  
}  

boolean removeAluno(int fileira, int carteira){
  
}

int[][] consultaAlunos(){
  
}

int exibeEspacoLivre(){
  
}

